#!/bin/bash

# latest commit
LATEST_COMMIT=$(git rev-parse HEAD)

function deployIfChanged() {
    FOLDER_COMMIT=$(git log -1 --format=format:%H --full-diff ${1}-frontend)
    if [ $FOLDER_COMMIT = $LATEST_COMMIT ]; then
        echo "${1}-frontend has changed since the last commit. Prepare deployment"
        cd ${1}-frontend
        cd ../
        ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive --only hosting:${1}
    fi
}

# install deployment tools
yarn init -y
yarn install
# OK to ignore the check since it's a one time use.
yarn add --ignore-workspace-root-check --dev firebase-tools

deployIfChanged 'main-site'
deployIfChanged 'samlang-demo'
deployIfChanged 'ten-web'

# cleanup
rm -rf node_modules/
rm package.json yarn.lock
