#!/bin/bash

function buildFrontend() {
    cd ${1}-frontend/
    yarn
    yarn build
    cd ../
}

function deployAppEngineJavaBackendApp() {
    echo "Deploying ${1}..."
    buildFrontend $1
    rm -rf ${1}-backend/src/main/webapp/static/
    mkdir ${1}-backend/src/main/webapp/static
    cp -R ${1}-frontend/build/. ${1}-backend/src/main/webapp/static
    cd ${1}-backend
    ./gradlew appengineDeploy
    cd ../
    echo "Finished Deploying $1."
}

function deployAppEngineNodeBackendApp() {
    echo "Deploying ${1}..."
    buildFrontend $1
    rm -rf ${1}-backend/public
    mkdir ${1}-backend/public
    cp -R ${1}-frontend/build/. ${1}-backend/public
    cd ${1}-backend
    yarn
    yarn deploy
    cd ../
    echo "Finished Deploying $1."
}

if [[ "$1" = "dispatch" ]]; then
    gcloud app deploy dispatch.yaml --project=dev-sam
elif [[ "$1" = "main-site" ]]; then
    echo "Deploying ${1}..."
    buildFrontend $1
    cd main-site-frontend
    firebase deploy
elif [[ "$1" = "admin" ]]; then
    deployAppEngineNodeBackendApp $1
elif [[ "$1" = "samlang-demo" ]]; then
    deployAppEngineJavaBackendApp $1
elif [[ "$1" = "ten-web" ]]; then
    deployAppEngineJavaBackendApp $1
elif [[ "$1" = "" ]]; then
    echo "No deployment target specified. Abort!"
    echo "Supported commands: deploy dispatch, deploy samlang-demo, deploy ten-web"
    exit 1
else
    echo "Unsupported deployment target!"
    exit 1
fi
