#!/bin/bash

function deployBackend() {
    cd ${1}/
    gcloud builds submit --tag gcr.io/developer-sam/${1}
    gcloud beta run deploy --platform managed --image gcr.io/developer-sam/${1} --memory 1Gi
    cd ../
}

if [[ "$1" = "samlang-demo-backend" ]]; then
    echo "Deploying ${1}..."
    deployBackend $1
elif [[ "$1" = "" ]]; then
    echo "No deployment target specified. Abort!"
    echo "Supported commands: deploy samlang-demo-backend"
    exit 1
else
    echo "Unsupported deployment target!"
    exit 1
fi
