#!/usr/bin/env node
/* eslint-disable no-console */
/* eslint-disable @typescript-eslint/no-var-requires */

const { execSync } = require('child_process');

try {
  execSync('tsc', { cwd: 'tools' });
} catch (error) {
  console.log(error.stdout.toString());
  console.log(error.stderr.toString());
}
require('./dist/generate').main();
